FROM public.ecr.aws/docker/library/python:3.12

WORKDIR /app

COPY requirements.txt ./

RUN python3.12 -m pip install -r requirements.txt -t .

COPY backtest_unit/ ./backtest_unit/

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app


ENTRYPOINT ["python", "-m"]
